= Literature Review

== The M&A Paradox: Systematic Failure in Valuation

Mergers and Acquisitions (M&A), despite serving as the primary mechanism for global capital reallocation, exhibit a persistent disconnect between the strategic intent and the actualised economic upshot. The "M&A Paradox" is defined by its statistical stationarity observed over the decades: across diverse economic regimes — from the monopoly consolidations of the early 20#super[th] century — the rate of value destruction has remained stubbornly high, estimated between 70% and 90% @MARTYNOVA20082148; @Christensen_Alton_Rising_Waldeck_2011. This historical invariance suggests that the failure is not merely situational, but roots from fundamental defects in the valuation mechanism respectively.

This section dissects the behavioural, structural, and epistemological defects that render the conventional predictive frameworks invalid.

=== The Behavioural Distortion: Hubris as Label Noise

"Synergy" — the super-additive value condition (V#sub[Merged] > V#sub[A] + V#sub[B]) — is the theoretical foundation justifying M&A transactions. While it predicates value creation, the empirical evidence indicates that acquisition premiums often reflect managerial overconfidence rather than economic reality. #cite(<Roll1986TheHH>, form: "author")'s (#cite(<Roll1986TheHH>, form: "year")) "Hubris Hypothesis" argues that acquiring managers systematically overestimate their ability to extract value, often mistaking a target's efficient market price for an underestimate of their own superior valuation.

This behavioural bias creates a "Synergy Trap" @sirower_synergy_1997 where the premium paid necessitates mathematically unattainable performance improvements just to break even, let alone create additional value. From a machine learning perspective, this introduces systematic "label noise" into financial datasets: the "deal value" is frequently a measure of executive ego rather than tangible intrinsic worth. Consequently, predictive models trained solely on historical transaction values risk fitting to this behavioural error rather than true economic potential.

=== Structural Blindness: The Failure of Orthogonal Due Diligence

Even discounting the managerial bias, the verification process itself is structurally flawed. Conventional due diligence operates in "silos": financial teams analyse balance sheets, legal teams scrutinise the contracts, and the operational teams assess the supply chains independently @angwin_mergers_2001.

This orthogonal approach fails to capture non-linear interaction effects. A financial audit may validate strong cash flows, while an operational audit independently flags a single-source supplier. In a linear summation, the deal passes. In reality, these risks are multiplicative: the collapse of a single-source supplier renders the cashflow non-existent. By treating the target as an isolated asset rather than a node within a complex adaptive system @frazzini-cohen-2008, traditional due diligence suffers from "structural blindness" to second-order systemic risks — a topological gap that necessitates a graph-based approach.

=== The Epistemological Barrier: Asymmetry and the Winner's Curse

The final barrier to accurate valuation is Information Asymmetry. #cite(<akerlof-1970>, form: "author")'s (#cite(<akerlof-1970>, form: "year")) "Market for Lemons" theory establishes that the seller (Target) inherently possesses superior information regarding asset quality than the buyer (Acquirer). In M&A, this manifests as a "winner's curse" — the probability that the winning bidder is the one who most dramatically overestimated the target's value due to incomplete disclosure @robert-1987.

While traditional finance relies on mandated filings (10-Ks) to reduce this asymmetry, targets can effectively obscure structural weaknesses — such as dependency on a fragile ecosystem — within the noise of standard reporting. This creates a theoretical imperative for the proposed methodology: if internal disclosures are subject to asymmetry and manipulation, objective truth must be sought in the external network structure. Unlike internal forecasts, a supplier's bankruptcy or a competitor's market share is verifiable external data. Thus, shifting the unit of analysis from the node (company) to the topology (dependencies) serves as an "Asymmetry Reduction Mechanism", bypassing the limitations of internal reporting.

=== Market-Driven Acquisitions: Valuation as Currency

A complementary explanation for persistent value destruction is provided by the "Stock Market Driven Acquisitions" model of #cite(<shleifer_vishny_2003>, form: "prose"), which argues that overvalued acquirers exploit their inflated equity as acquisition currency, generating deals motivated by market timing rather than fundamental synergy. Under this framework, acquisition waves correlate with periods of market overvaluation — the acquirer "cashes in" its overpriced stock before the market corrects. This theory implies that a significant proportion of M&A transactions are driven by _relative misvaluation_ rather than operational complementarity, further contaminating the label space for predictive models as the observed CAR reflects market correction dynamics rather than genuine synergy realisation. Critically, this provides additional justification for the binary classification framing adopted in this study (§2.3.4): the precise _magnitude_ of CAR is confounded by market-timing noise, whereas the _direction_ (positive vs. negative) more reliably captures whether fundamental synergy was present.

== Sophisticated Linearity: Computational Evolution and the Persistent Tabular Paradigm in M&A Prediction

The failure of subjective valuation (Hubris) and qualitative verification (due-diligence) created a vacuum that quantitative models attempted to fill. The history of M&A prediction is defined by a methodological arms race — from simple linear discriminants to complex ensemble learners. Yet, a further critical inspection reveals that while the computational complexity of these models has increased, their fundamental assumption remains stagnant: they treat firms as isolated data points (Independent and Identically Distributed), ignoring the complex, non-linear ecosystem in which they operate. This section argues that current predictive accuracy has hit an asymptotic ceiling precisely because it remains trapped in this "Tabular Paradigm".

=== The Econometric Era: The Fallacy of Linearity

The first generation of predictive models, pioneered by #cite(<PALEPU19863>, form:"prose"), utilised Logit and Probit regression to predict acquisition likelihood based on financial ratios. These models operated on a "Linearity Bias", assuming a monotonic relationship between financial metrics and synergy potential — such as assuming higher growth is unconditionally superior. In reality, financial relationships are interdependent and non-linear; #cite(<prediction_barnes_1990>, form: "prose") demonstrated that moderate leverage signals discipline while high leverage signals distress, creating relationships that linear models fundamentally misinterpret.

Crucially, this linearity persists in modern applications. Recent studies @aidriven_zhang_2024 utilising random forests rely on feature engineering that discretises continuous financial data (e.g. converting debt ratios into categorical bins) before model training. By forcing high-dimensional, pre-processed tabular formats, these models crystallise human bias into irreversible feature sets. They become automated versions of the same flawed heuristics used by human analysts, but legitimised by the false confidence of algorithmic sophistication.

=== The "Tabular Trap" of Modern NLP and Deep Learning

The advent of Natural Language Processing (NLP) and Deep Learning promised to transcend these limitations. Researchers started to use Transformers such as BERT, RoBERTa, and FinBERT to extract "strategic intent" from 10-K filings. While these techniques successfully process unstructured text, a critical review of recent literature reveals a systematic failure to leverage this data topologically — a phenomenon we term the "Tabular Trap".

Recent high-impact studies illustrate this pervasive limitation. #cite(<zhao2020bertbasedsentimentanalysis>) employed BERT to analyse sentiment in M&A news, demonstrating significant accuracy gains over bag-of-words models. However, their architecture flattened the rich semantic output into a statistic vector for standard XGBoost Classifier, discarding the relational context of the mentioned entities. The model effectively treats the text as an attribute of an isolated node, ignoring the network effects that define its real-world value.

Similarly, a study by #cite(<Elhoseny_Metawa_Sztano_El-Hasnony_2022>, form: "prose") utilised deep neural networks optimised with AWOA (Ameliorative Whale Optimization Algorithm) to predict financial distress, achieving significantly higher temporal accuracy than conventional machine learning models. Yet, the model treated each firm as an isolated entity, processing only its individual financial metrics and explicitly ignoring the contagion effects from distressed supply-chain partners or broader network dependencies.

This reductionism is not an isolated oversight but the field's dominant paradigm: despite access to advanced architectures #cite(<attentionisallyouneed>, form: "prose"), researchers deploy "Ferrari engines" (transformers) to power "wooden carts" (tabular MLPs). For instance, two companies might have identical "supply chain risk" scores in their 10-Ks (high semantic similarity). A standard NLP model treats them as identical risks; however, if Company A's supplier is a stable giant and Company B's supplier is a bankrupt startup, the _real_ risk is vastly different. Since standard Deep Learning models (SVMs, MLPs, LSTMs) lack a graph operator, they cannot see this distinction. They process the "symptom" (the text) but ignore the "cause" (the network topology). This collective blindness necessitates a shift to graph-based learning not merely as an alternative, but as the only mechanism capable of recovering the lost signal of systemic interdependency.

== The "Semantic Turn": Recovering the Missing Variable

The inadequacy of quantitative financials to capture intangible synergy drivers — such as corporate culture, risk appetite, and strategic intent — compelled a "Semantic Turn" in Financial Research. This shift is not merely additive but remedial; it addresses the "omitted variable bias" inherent in tabular models, where financial ratios typically explain only a fraction of the variance in M&A outcomes (pseudo R#super[2] < 0.10), as documented across multiple econometric studies from #cite(<PALEPU19863>, form: "prose") to comprehensive handbook surveys of the takeover literature @betton_eckbo_thorburn_2008. The remaining explanatory power is encoded in the unstructured text of 10-K filings. However, the evolution of textual analysis has been defined by a struggle between computational tractability and semantic fidelity. This section critiques the progression from rudimentary frequency-based methods to advanced transformer architectures, arguing that even sophisticated models frequently misdirect their power, optimising for "document classification" rather than the nuanced quantification of strategic fit.

=== The Limits of the "Bag-of-Words" Paradigm: Compositional Blindness

The seminal work in financial NLP is undoubtedly #cite(<LOUGHRAN_MCDONALD_2011>, form: "prose"), who demonstrated that terms like "liability" are often neutral legal descriptors rather than negative indicators. To address this, they constructed domain-specific lexicons to measure sentiment based on word frequency. While this approach marked a significant advance, it remains trapped in the "Bag-of-Words" (BoW) paradigm. BoW models treat a document as a disorganised pile of words, discarding syntax, grammar, and, crucially, intent. A frequency-based model sees no distinction between "We have significant exposure to risk" and "We have eliminated exposure to risk", as the word counts are identical.

More critically, BoW models are "compositionally blind". Financial reporting is often a strategic game where firms utilise complex sentence structures to obfuscate negative news. In the high-stakes environment of M&A, where a single conditional clause ("subject to") can invert the meaning of a multi-billion dollar liability statement, reliance on such frequency-based heuristics introduces catastrophic ambiguity. Yet, this limitation persists; recent studies such as #cite(<Demers_Wang_Wu_2024>, form: "prose") continue constructing domain-specific lexicons for corporate disclosures while #cite(<Acheampong_Mousavi_Gozgor_Yeboah_2025>, form: "prose") continue to proxy financial constraints using simple lexicon-based indices, and #cite(<Garcia_Hu_Rohrer_2020>, form: "prose") develop new finance dictionaries through market-based validation, essentially ignoring the strategic obfuscation inherent in corporate disclosures.

=== The Transformer Revolution: Contextual Disambiguation via FinBERT

The release of BERT (Bidirectional Encoder Representations from Transformers) by #cite(<2.3.2-DEVLIN2018>, form:"prose") rendered lexicon-based approaches obsolete by introducing "contextual embeddings". Unlike BoW, which assigns a static value to a word, BERT generates dynamic vectors based on the surrounding text, allowing it to mathematically solve polysemy.

In the financial domain, this architecture was specialised by #cite(<2.3.2-ARACHI2019>, form:"prose") into FinBERT, a model pretrained specifically on corporate filings. The advantage of FinBERT is conceptual: it solves the ambiguity of financial language. It "knows" that "maturity" in a bond prospectus refers to a repayment date, not emotional development. By compressing entire documents into dense vector representations, FinBERT captures latent strategic signals — such as the similarity between an acquirer's "Risk Factor" and target's Management Discussion and Analysis — that simple word counting misses entirely. This capability is essential for distinguishing between "Semantic Fit" (alignment of strategy) and "Semantic Dissonance" (clash of cultures) without relying on brittle, easily manipulated dictionaries.

=== The Gap in Textual M&A Research: The Prediction Target

Despite the availability of these powerful semantic tools, their application to M&A synergy prediction remains surprisingly fragmented. Early multimodal papers established that text contains predictive signal, but modern successors often misdirect this power toward simplistic targets.

A critical review of recent works (2022–24) reveals a persistent gap. #cite(<2.3.3-Hajek_2024>, form:"prose") employed FinBERT for M&A news sentiment analysis and #cite(<2.3.3-Han_2023>, form:"prose") utilised RoBERTa transformers to identify M&A targets from textual disclosures, both achieving high accuracy in "acquisition likelihood" prediction (Binary: "target" vs. "non-target"). While #cite(<2.3.3-Elhoseny_2022_Deep_Learning_Distress>, form:"prose") leveraged deep neural networks for financial distress prediction, forecasting categorical outcomes rather than continuous value creation.

However, these models predict binary outcomes — deal occurrence or financial distress — metrics valuable for trading strategies but insufficient for corporate strategy. They predict market activity rather than economic productivity.

Furthermore, studies that do attempt to predict outcomes often utilise generic BERT models, diluting the signal with noise from general English. There is a conspicuous absence of research that fuses domain-specific embeddings (FinBERT) with topological data (Graphs) to predict synergy outcomes. This represents the critical research gap: the field possesses the correct tools (FinBERT) but applies them to the wrong problems in isolation.

=== The Case for Directional Classification over Continuous Regression

While the theoretical ideal is to predict the continuous magnitude of CAR, empirical evidence demonstrates that the noise floor inherent in short-window event studies renders continuous regression targets largely intractable for machine learning models. The signal-to-noise ratio of daily abnormal returns is persistently low (pseudo R#super[2] < 0.10), as documented across econometric studies from #cite(<PALEPU19863>, form: "prose") to comprehensive surveys of takeover prediction @betton_eckbo_thorburn_2008. This observation is consistent with the Efficient Market Hypothesis's implication that the _magnitude_ of market surprise is fundamentally unpredictable, whereas its _direction_ — positive versus negative synergy — contains learnable signal rooted in pre-announcement fundamentals.

Consequently, this project reframes the prediction target as a binary classification: $y_i = 1$ if $"CAR"_i > 0$ (value-creating deal) and $y_i = 0$ otherwise (value-destructive). This formulation preserves the economic interpretation — distinguishing synergistic from value-destructive deals — while aligning the prediction target with what the feature space can realistically support. This directional framing is consistent with the classification approaches adopted by recent M&A machine learning studies @aidriven_zhang_2024; @ajayi_ml_ma_2022 and shifts the evaluation metric from R#super[2] to AUC-ROC.

The choice of AUC-ROC over alternative classification metrics (e.g. Accuracy, F1) is itself methodologically significant. In M&A datasets, deal outcomes are not uniformly distributed — the ratio of value-creating to value-destructive deals varies by market cycle and sample window. Accuracy under such class imbalance can be misleadingly inflated by a naïve majority-class predictor. AUC-ROC, by contrast, evaluates a model's discrimination ability across _all_ classification thresholds, measuring the probability that a randomly chosen positive instance (synergistic deal) ranks higher than a randomly chosen negative instance. This threshold-invariant property makes it the preferred metric for probabilistic financial classifiers, where the cost of a false positive (predicting synergy for a value-destructive deal) differs substantially from a false negative. AUC-ROC is therefore adopted as the primary evaluation metric throughout this study, with Accuracy and F1-score reported as secondary indicators for completeness.

This project aims to close that gap by directing the full power of contextual embeddings toward the classification of post-merger synergy direction.

== The "Topological Turn": Recovering the Lost Signal of Dependency

Financial ratios describe a firm's capacity; textual disclosures reveal its intent. Yet, neither captures its structural power — the value derived from its position within the industrial ecosystem. The limitations of isolated tabular models (Section 2.2) and siloed textual analysis (Section 2.3) necessitate a "Topological Turn" in financial computing. This paradigm shift posits that firm value is fundamentally relational, defined by dependencies on suppliers, customers, and competitors that tabular models systematically discard through their independence assumptions.

This section establishes the economic theoretical basis for graph-based modelling as a mechanism for information recovery and critiques the current state of Graph Neural Network (GNN) applications in M&A.

=== The Economic Basis: Supply Chain Momentum and Information Friction

The justification for using graph structures is grounded in market physics, not just computational novelty. #cite(<frazzini-cohen-2008>, form:"prose") established the "Physics of the Market" by proving that economic shocks to a supplier do not immediately price into the customer firm due to information friction. Instead, these shocks travel across the supply chain with a measurable lag, creating a "predictable momentum" that isolated analysis misses.

For M&A, synergy potential is a property of ecosystem health, not an intrinsic characteristic of the target. A target with strong internal financials but a fragile, insolvent supplier network is a "Lemon" in disguise @akerlof-1970. Traditional due diligence, which typically stops at first-order relationships (direct suppliers), fails to capture higher-order contagion risks — such as a bankruptcy in a tier-2 supplier — that mathematically propagate through the network topography. By modelling these dependencies explicitly, GNNs recover the signal that tabular models discard.

=== Graph Neural Networks: From Transductive to Inductive Learning

To capture these dependencies, modern research utilises Graph Neural Networks (GNNs). The foundational architecture was established by #cite(<kipf_welling_2017>, form: "prose"), who introduced Graph Convolutional Networks (GCNs), extending spectral graph theory into a scalable neighbourhood aggregation framework. GCNs demonstrated that node representations could be enriched by recursively aggregating information from local neighbourhoods, achieving state-of-the-art performance on citation and social networks.

However, applying GNNs to M&A presents a unique challenge: the "Cold Start" problem. Private companies (a primary source of M&A targets) often lack extensive historical data, and GCNs remain _transductive_ — they require all nodes to be present during training — rendering them incapable of generating embeddings for nodes absent during the training phase.

The introduction of GraphSAGE by #cite(<3.1HamiltonYL17>, form:"prose") resolved this by enabling "Inductive Learning": rather than memorising specific node embeddings, GraphSAGE learns _aggregation functions_ that generate representations for completely unseen nodes. This is business-critical for M&A. #cite(<2.4.2-venutti2021>, form: "prose") demonstrated GraphSAGE predicting acquisitions for private enterprise companies with 81.79% accuracy, proving it can infer valuation of data-scarce targets from their public ecosystem connections. It effectively learns the "rules of the ecosystem" rather than the "map of the ecosystem", making it the only viable architecture for private market valuation where historical data is absent.

The choice of GraphSAGE over alternative GNN architectures (GCN, GAT, GIN) in this study is therefore driven by three converging requirements: (i) the inductive capability to generalise to unseen firms; (ii) the heterogeneous edge-type support necessary for modelling distinct `supplies_to` and `competes_with` relationships; and (iii) the computational scalability afforded by its mini-batch neighbourhood sampling strategy, which permits training on graphs with tens of thousands of nodes without full-graph materialisation.

=== The "Wrong Target" Problem: Trading vs. Strategy

Despite the theoretical fit of GNNs for M&A, a critical review of literature from 2023–2024 reveals a persistent misalignment: researchers are applying advanced topology to the wrong prediction targets.

Recent works display impressive engineering sophistication. #cite(<2.4.3-wang2024>, form:"prose") introduced dynamic GNNs to model stock market movements with high temporal fidelity, while #cite(<2.4.3-he2023graphneuralnetworkssupply>) successfully utilised GNNs to predict supply chain contagion risk. However, these models invariably predict market activity (price change or binary distress) rather than corporate productivity (synergy). #cite(<2.4.3-wang2024>, form: "prose") built a magnificent telescope but pointed it at the ground — optimising for short-term trading signals rather than long-term strategic value.

There is a conspicuous absence of research that links these topological risks to post-merger synergy (Cumulative Abnormal Return — CAR). The field has perfected the prediction of "who will move", but neglected the prediction of "will the move create value?". This constitutes the primary research gap. Current models can tell a CEO that a target has "high network risk", but they cannot quantify whether the potential synergy justifies that risk.

This project aims to bridge this gap by applying the inductive power of GraphSAGE to the binary synergy classification of CAR direction, establishing the first framework to align the "Topological Turn" with the economic imperative of value creation.

== Synthesis: The Multimodal Imperative

The critical review of existing literature reveals a landscape defined by "methodological orthogonality". Financial models measure capacity but lack context; textual models capture intent but lack structure; and topological models measure position but typically misdirect their predictive power toward deal likelihood. The persistent failure of M&A valuation (70%–90% failure rate) is therefore not due to a lack of signal in any single domain, but the absence of a unified framework capable of resolving the interactions between them.

This project posits that the "Synergy variable" is latent within the intersection of these modalities. Consequently, reliance on any mono-modal architecture is not merely suboptimal but constitutes an information-theoretic limitation — one cannot reconstruct the high-dimensional shape of value creation from low-dimensional projections alone.

=== The Case for Heterogeneous Late Fusion

The argument for a multimodal architecture rests on the hypothesis of "complementary variance". Traditional approaches implicitly assume that financial, textual, and topological features are collinear — that a firm with strong financials will naturally have a strong network. Empirical reality contradicts this; a firm may exhibit high capital adequacy (Financial) yet suffer from high supply chain fragility (Topological) and strategic incoherence (Textual). A mono-modal model is mathematically blind to these divergences.

A critical architectural consideration in multimodal fusion is the choice between _end-to-end joint training_ and _decoupled late fusion_. While joint training theoretically permits cross-modal gradient flow, it is poorly suited to the constraints of financial M&A datasets: sample sizes are typically in the low thousands (N ≈ 2,800–5,000), far below the data requirements for stable end-to-end deep learning. #cite(<3.1Baltrušaitis-Ahuja>, form: "prose") formally categorise this as "late fusion", where independently learned representations are concatenated and fed into a separate inference engine.

In the financial domain specifically, #cite(<3.1Chen_2016>, form: "prose") demonstrated that gradient-boosted tree ensembles (XGBoost) consistently outperform neural networks on tabular data with heterogeneous feature types — precisely the structure of a concatenated multimodal vector containing financial ratios, PCA-compressed text embeddings, and graph topology scores. The XGBoost architecture is further selected over alternative ensemble methods (Random Forest, LightGBM) for its built-in L1/L2 regularisation, which provides structural overfitting protection critical when the feature-to-sample ratio is high (249 features to ~2,800 training observations), and for its native handling of missing values — a practical necessity when text and graph coverage is incomplete across the deal sample.

Furthermore, the integration of graph data necessitates a shift from homogeneous to heterogeneous representations. Treating all inter-firm connections as identical edges introduces semantic noise. A `supplies_to` relationship implies dependency and risk propagation, whereas a `competes_with` relationship implies market concentration and pricing power. A Heterogeneous Graph Neural Network (HGNN) preserves these distinct semantic channels, allowing the model to learn opposing weighting functions for different edge types — effectively distinguishing between "risk-generating" and "value-generating" connections.

The SHAP framework @lundberg_shap_2017 enables post-hoc decomposition of each modality's marginal contribution, grounded in cooperative game theory (Shapley values), providing the interpretability demanded by financial stakeholders. This is methodologically preferred over permutation importance (which is computationally expensive and unstable under feature correlation) and over attention-weight inspection (which recent work has shown to be unreliable as a proxy for feature importance in transformer architectures).

=== Research Hypotheses

To validate this multimodal framework, this study creates a controlled experimental environment to test three specific mechanisms of value creation. The following hypotheses are proposed:

#text(weight: "semibold")[- H#sub[1]: The Topological Alpha Hypothesis]

The inclusion of second-order neighbour embeddings (via GraphSAGE) will yield a statistically significant increase in AUC-ROC ($p < 0.05$, paired $t$-test) for binary synergy classification relative to finance-only baselines under 5-fold stratified cross-validation. This predictive gain will be disproportionately concentrated within "Supply Chain Dependent" sectors (SIC 20–49) compared to "Asset Light" sectors (SIC 60–79), reflecting the hypothesis that graph embeddings recover signal proportional to the structural density of the industrial ecosystem.

The _paired $t$-test_ is selected as the significance test because the comparison is between two models (M1 vs. M3) evaluated on the _same_ cross-validation folds, producing naturally paired observations. This controls for fold-level variance that would otherwise inflate standard errors in an unpaired test. AUC-ROC is compared across folds rather than raw accuracy, as it is robust to the class imbalance observed in the synergy label distribution.

#text(weight: "semibold")[- H#sub[2]: The Semantic Divergence Hypothesis]

The predictive relationship between semantic similarity and synergy is conditional on the document section. Specifically, high cosine similarity in strategic disclosure (MD&A) will positively correlate with CAR (alignment), whereas high similarity in risk disclosure (Risk Factors) will negatively correlate with CAR (concentration), refuting the standard NLP assumption of monotonic sentiment utility.

This hypothesis is tested via bivariate OLS regression ($"CAR"_i = beta_0 + beta_1 dot "sim"_i^"MDA" + beta_2 dot "sim"_i^"RF" + epsilon_i$), selected because the continuous nature of both the independent (cosine similarity) and dependent (raw CAR) variables makes regression the natural framework. The bivariate specification — simultaneously including both similarity scores — is critical, as it controls for confounding between the two textual dimensions: firms with high MD&A similarity often also exhibit high Risk Factor similarity, and only a joint model can isolate their independent effects. OLS is preferred over non-linear alternatives (polynomial regression, GAMs) to maintain interpretability of the coefficient signs ($beta_1 > 0$, $beta_2 < 0$), which directly operationalise the hypothesis.

#text(weight: "semibold")[- H#sub[3]: The Topological Arbitrage Hypothesis]

Acquirer nodes exhibiting high betweenness centrality (bridge nodes connecting disparate communities) will exhibit statistically compressed variance in |CAR| outcomes compared to peripheral nodes, as measured by Levene's test for equality of variance across betweenness centrality quantile groups. This compression reflects the "dampening" effect of bilateral supplier dependencies that constrain both upside synergy capture and downside disruption risk for topologically central firms.

_Levene's test_ is chosen over the classical Bartlett's test for two reasons: (i) it does not assume normality of the underlying distribution — a critical property given that |CAR| is right-skewed with heavy tails characteristic of financial return data; and (ii) it is robust to the unequal group sizes that naturally arise from quantile binning of power-law-distributed betweenness centrality values. The use of quantile-based binning (rather than equal-width bins) ensures that each group contains sufficient observations for reliable variance estimation, accommodating the extreme skewness of centrality distributions where the majority of nodes have near-zero betweenness.


#bibliography("works.bib", style: "harvard-cite-them-right")