import json
import os

os.makedirs('notebooks', exist_ok=True)
os.makedirs('docs/figures', exist_ok=True)

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# M&A Synergy Prediction: Final Visualizations\n",
            "This notebook generates the four high-dimensional visualizations for the final dissertation:\n",
            "1. **The Topological Alpha Ego-Network**\n",
            "2. **The Multimodal SHAP Summary Plot**\n",
            "3. **The H3 Volatility Funnel Scatterplot**\n",
            "4. **The ROC-AUC Capability Gap**"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import sys\n",
            "from pathlib import Path\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import networkx as nx\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import shap\n",
            "import json\n",
            "import torch\n",
            "import torch_geometric\n",
            "from xgboost import XGBClassifier\n",
            "from sklearn.metrics import roc_curve, auc\n",
            "from sklearn.impute import SimpleImputer\n",
            "from sklearn.model_selection import StratifiedKFold\n",
            "\n",
            "# Ensure scripts path is available\n",
            "sys.path.insert(0, str(Path(os.getcwd()).parent / 'scripts'))\n",
            "try:\n",
            "    from training_utils import load_and_prepare_data, get_feature_configs\n",
            "except ImportError:\n",
            "    sys.path.insert(0, str(Path(os.getcwd()) / 'scripts'))\n",
            "    from training_utils import load_and_prepare_data, get_feature_configs\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "sns.set_theme(\n",
            "    style=\"whitegrid\",\n",
            "    font_scale=1.05,\n",
            "    rc={\n",
            "        \"axes.edgecolor\": \"#333333\",\n",
            "        \"axes.linewidth\": 0.8,\n",
            "        \"axes.spines.right\": False,\n",
            "        \"axes.spines.top\": False,\n",
            "        \"grid.alpha\": 0.2,\n",
            "        \"grid.linestyle\": \"-\",\n",
            "    },\n",
            ")\n",
            "\n",
            "data_path = '../data/processed/final_multimodal_dataset.csv'\n",
            "if not os.path.exists(data_path):\n",
            "    data_path = 'data/processed/final_multimodal_dataset.csv'\n",
            "\n",
            "fig_dir = '../docs/figures'\n",
            "if not os.path.exists('../docs'):\n",
            "    fig_dir = 'docs/figures'\n",
            "os.makedirs(fig_dir, exist_ok=True)\n",
            "\n",
            "subset, y_cont = load_and_prepare_data()\n",
            "y_binary = (y_cont > 0).astype(int)\n",
            "configs = get_feature_configs(subset)\n",
            "X_m3 = subset[configs['M3']['cols']]\n",
            "X_m3_imputed = pd.DataFrame(SimpleImputer(strategy='median').fit_transform(X_m3), columns=X_m3.columns)\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. The \"Topological Alpha\" Ego-Network\n", "Visualizing a complex supply chain network surrounding a specific acquisition to show the structural context."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "hetero_graph_path = '../data/interim/hetero_supply_chain_graph.pt'\n",
            "hetero_meta_path = '../data/interim/hetero_graph_metadata.json'\n",
            "if not os.path.exists(hetero_graph_path):\n",
            "    hetero_graph_path = 'data/interim/hetero_supply_chain_graph.pt'\n",
            "    hetero_meta_path = 'data/interim/hetero_graph_metadata.json'\n",
            "\n",
            "graph_data = torch.load(hetero_graph_path, weights_only=False)\n",
            "with open(hetero_meta_path, 'r') as f:\n",
            "    metadata = json.load(f)\n",
            "\n",
            "homo_data = graph_data.to_homogeneous()\n",
            "G_nx = torch_geometric.utils.to_networkx(homo_data, to_undirected=True)\n",
            "degrees = dict(G_nx.degree())\n",
            "hub = sorted(degrees.items(), key=lambda x: x[1], reverse=True)[2][0]\n",
            "\n",
            "neighbors_k = nx.single_source_shortest_path_length(G_nx, hub, cutoff=2)\n",
            "sub_G = G_nx.subgraph(neighbors_k.keys()).copy()\n",
            "\n",
            "plt.figure(figsize=(8, 8))\n",
            "pos = nx.spring_layout(sub_G, seed=42, k=0.2)\n",
            "betweenness = nx.betweenness_centrality(sub_G)\n",
            "node_color = [betweenness[n] for n in sub_G.nodes()]\n",
            "\n",
            "nodes = nx.draw_networkx_nodes(\n",
            "    sub_G, pos,\n",
            "    node_size=[40 + 600 * betweenness[n] for n in sub_G.nodes()],\n",
            "    node_color=node_color,\n",
            "    cmap='plasma', alpha=0.9\n",
            ")\n",
            "nx.draw_networkx_edges(sub_G, pos, alpha=0.15, edge_color='#777777')\n",
            "\n",
            "try:\n",
            "    id_to_tkr = {v: k for k, v in metadata['company_to_id'].items()}\n",
            "    hub_label = id_to_tkr.get(hub, str(hub))\n",
            "except:\n",
            "    hub_label = str(hub)\n",
            "\n",
            "nx.draw_networkx_nodes(sub_G, pos, nodelist=[hub], node_color='#ffdd00', edgecolors='black', node_size=900)\n",
            "nx.draw_networkx_labels(sub_G, pos, labels={hub: hub_label}, font_size=10, font_weight='semibold')\n",
            "\n",
            "plt.title(f'Topological Alpha: Ego-Network for {hub_label}', fontsize=14, weight='semibold')\n",
            "plt.text(0.02, 0.98, 'Hub represents central supply-chain position\\ncoloring indicates Information Brokerage (Betweenness)', transform=plt.gca().transAxes, fontsize=9, verticalalignment='top', color='#555555', bbox=dict(facecolor='white', alpha=0.8, edgecolor='none', pad=3))\n",
            "plt.colorbar(nodes, label='Betweenness Centrality', shrink=0.7)\n",
            "plt.axis('off')\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 2. The Multimodal SHAP Summary Plot\n", "Proving that graph embeddings and text embeddings materially impact the predictions."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "model = XGBClassifier(eval_metric='auc', random_state=42, use_label_encoder=False)\n",
            "model.fit(X_m3_imputed, y_binary)\n",
            "explainer = shap.TreeExplainer(model)\n",
            "shap_values = explainer.shap_values(X_m3_imputed)\n",
            "\n",
            "plt.figure(figsize=(7.5, 9))\n",
            "shap.summary_plot(shap_values, X_m3_imputed, max_display=15, show=False, plot_size=None, cmap='Spectral_r', alpha=0.7)\n",
            "plt.title('Multimodal Feature Impact (SHAP Summary Plot)', fontsize=14, weight='semibold')\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. The \"H3 Volatility Funnel\" Scatterplot\n", "Scatterplot of Betweenness Centrality vs Absolute CAR with a seaborn KDE density overlay."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "G = nx.DiGraph()\n",
            "G.add_nodes_from(range(graph_data['company'].num_nodes))\n",
            "for edge_type in [('company', 'supplies', 'company'), ('company', 'buys_from', 'company')]:\n",
            "    ei = graph_data[edge_type].edge_index\n",
            "    for i in range(ei.size(1)):\n",
            "        G.add_edge(ei[0, i].item(), ei[1, i].item())\n",
            "\n",
            "betweenness_full = nx.betweenness_centrality(G)\n",
            "\n",
            "ticker_to_id = metadata['ticker_to_id']\n",
            "deal_to_acq_ticker = metadata['deal_to_acq_ticker']\n",
            "records = []\n",
            "for deal_id_str, acq_ticker in deal_to_acq_ticker.items():\n",
            "    deal_id = int(deal_id_str)\n",
            "    node_id = ticker_to_id.get(acq_ticker)\n",
            "    if node_id is not None:\n",
            "        records.append({'deal_id': deal_id, 'Acq_Betweenness': betweenness_full.get(node_id, 0.0)})\n",
            "\n",
            "cent_df = pd.DataFrame(records)\n",
            "subset_copy = subset.copy()\n",
            "subset_copy['deal_id'] = subset_copy.index\n",
            "subset_copy['car'] = y_cont\n",
            "merged = subset_copy.merge(cent_df, on='deal_id', how='inner')\n",
            "merged['abs_car'] = merged['car'].abs()\n",
            "plot_df = merged[['Acq_Betweenness', 'abs_car']].dropna()\n",
            "\n",
            "plt.figure(figsize=(10, 6))\n",
            "sns.kdeplot(data=plot_df, x='Acq_Betweenness', y='abs_car', fill=True, cmap='Blues', alpha=0.25, levels=8, thresh=0.02, warn_singular=False)\n",
            "sns.scatterplot(data=plot_df, x='Acq_Betweenness', y='abs_car', color='#1f3b7c', alpha=0.3, s=12, edgecolor='none')\n",
            "sns.regplot(data=plot_df, x='Acq_Betweenness', y='abs_car', scatter=False, color='#d62728', line_kws={'linestyle':'--', 'linewidth': 1.5})\n",
            "\n",
            "plt.title('H3 Volatility Funnel: Information Transparency Effect', fontsize=14, weight='semibold')\n",
            "plt.annotate('Information Transparency Zone\\n(High Centrality bounded by Low Variance)', xy=(0.04, 0.05), xytext=(0.04, 0.25), fontsize=10, weight='bold', color='#1f3b7c', arrowprops=dict(arrowstyle='->', color='#1f3b7c', lw=1.2, connectionstyle='arc3,rad=0.2'))\n",
            "plt.xlabel('Acquirer Betweenness Centrality', fontsize=11)\n",
            "plt.ylabel('Absolute CAR', fontsize=11)\n",
            "plt.grid(alpha=0.2, linewidth=0.5)\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 4. The ROC-AUC Capability Gap\n", "The ultimate proof of your dissertation adding value: plotting the AUC difference between Financial-only (M1) and Multimodal (M3) features."]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "X_m1 = subset[configs['M1']['cols']]\n",
            "X_m1_imputed = pd.DataFrame(SimpleImputer(strategy='median').fit_transform(X_m1), columns=X_m1.columns)\n",
            "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
            "\n",
            "def get_cv_predictions(X, y):\n",
            "    y_probs = np.zeros(len(y))\n",
            "    for train_idx, test_idx in cv.split(X, y):\n",
            "        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]\n",
            "        y_train = y.iloc[train_idx]\n",
            "        mod = XGBClassifier(eval_metric='auc', random_state=42, use_label_encoder=False)\n",
            "        mod.fit(X_train, y_train)\n",
            "        y_probs[test_idx] = mod.predict_proba(X_test)[:, 1]\n",
            "    return y_probs\n",
            "\n",
            "y_binary_s = pd.Series(y_binary)\n",
            "probs_m1 = get_cv_predictions(X_m1_imputed, y_binary_s)\n",
            "probs_m3 = get_cv_predictions(X_m3_imputed, y_binary_s)\n",
            "\n",
            "fpr_m1, tpr_m1, _ = roc_curve(y_binary, probs_m1)\n",
            "fpr_m3, tpr_m3, _ = roc_curve(y_binary, probs_m3)\n",
            "auc_m1 = auc(fpr_m1, tpr_m1)\n",
            "auc_m3 = auc(fpr_m3, tpr_m3)\n",
            "\n",
            "fpr_grid = np.linspace(0.0, 1.0, 1000)\n",
            "tpr_m1_interp = np.interp(fpr_grid, fpr_m1, tpr_m1)\n",
            "tpr_m3_interp = np.interp(fpr_grid, fpr_m3, tpr_m3)\n",
            "\n",
            "plt.figure(figsize=(7.5, 7))\n",
            "plt.plot(fpr_m3, tpr_m3, color='#ff7f0e', lw=2, label=f'M3 Multimodal (AUC = {auc_m3:.3f})')\n",
            "plt.plot(fpr_m1, tpr_m1, color='#1f77b4', lw=2, label=f'M1 Financials Only (AUC = {auc_m1:.3f})')\n",
            "plt.plot([0, 1], [0, 1], color='#999999', lw=1, linestyle='--')\n",
            "\n",
            "plt.fill_between(fpr_grid, tpr_m1_interp, tpr_m3_interp, where=tpr_m3_interp >= tpr_m1_interp, color='#ffbb78', alpha=0.25, label=f'\"Topological Alpha\" Gap (\\u0394AUC = {auc_m3 - auc_m1:.3f})')\n",
            "\n",
            "plt.xlabel('False Positive Rate', fontsize=11)\n",
            "plt.ylabel('True Positive Rate', fontsize=11)\n",
            "plt.title('ROC-AUC Capability Gap: Multimodal vs Financial Baseline', fontsize=14, weight='semibold')\n",
            "plt.annotate('Small but consistent\\n\\'Topological Alpha\\' Gap', xy=(0.45, 0.48), xytext=(0.65, 0.35), fontsize=11, weight='bold', color='#d62728', arrowprops=dict(arrowstyle='->', color='#d62728', lw=1.5, connectionstyle='arc3,rad=-0.2'))\n",
            "plt.xlim(0, 1)\n",
            "plt.ylim(0, 1.02)\n",
            "plt.grid(alpha=0.2, linewidth=0.5)\n",
            "plt.legend(frameon=False, fontsize=10, loc='lower right')\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open('notebooks/final_visualizations.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("Created notebooks/final_visualizations.ipynb with updated aesthetics successfully.")
